image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

environment:
  nodejs_version: "latest"

install:

  - ps: Install-Product node '' x64
  - npm install
  - docker-compose up &
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true