image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

init:
  - git config --global core.autocrlf true

environment:
  - nodejs_version: "latest"

platform:
  - x64

install:

  - powershell ./build.ps1
  - cmd: powershell ./build.ps1

  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - docker-compose up &
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true