image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: latest

install:

  - ps: Install-Product node $env:nodejs_version
  - npm install
  - docker-compose up &
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true